### ISSUE TITLE
Feature Request: Add Ability To Choose Days of the week

### ISSUE THREAD

**Issue by robp2175** [concerto/concerto_content_scheduling#21]
Would it be possible to add the days of the week to a recurring schedule. For example, I want the content to be displayed every Saturday from 8am until 11am?

**Comment by mfrederickson** [comment]
This functionality is already there.  Just choose a frequency of weekly, then choose the day and specify the time.
![image](https://cloud.githubusercontent.com/assets/473165/5634765/350a7b26-958f-11e4-8cc1-861d7047b687.png)

**Comment by robp2175** [comment]
It is not showing up like that for me. All I see is this
![screen shot 01-06-15 at 02 38 pm](https://cloud.githubusercontent.com/assets/8832179/5634846/6538211e-95b1-11e4-98f4-f5df0d912139.PNG)

**Comment by mfrederickson** [comment]
Yes, once you choose set schedule then a pop up window should come up (make sure you allow those).

**Comment by robp2175** [comment]
Not getting the popup even with popups unblocked.

Sent from my iPhone

On Jan 6, 2015, at 4:05 PM, Marvin Frederickson <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, once you choose set schedule then a pop up window should come up (make sure you allow those).

-

**Comment by robp2175** [comment]
I have tried this in every browser chrome, firefox, and ie. I typically use Firefox version 34.0.5.

I think something must have hiccupped during install.

**Comment by robp2175** [comment]
Can you please go over the install process just to make sure I did not miss anything. I am new to working with Ruby so your patience is appreciated.

**Comment by mfrederickson** [comment]
It works fine for me when I use Chrome.  When I use IE version 11  (and press F12 to turn on the tools pane) then as soon as I click the OK button in the "Repeat" window it pops up the debugger and says that `JSON is undefined in recurring_select.js`.  Do you get this also?  (It looks like you are using IE).

![image](https://cloud.githubusercontent.com/assets/473165/5650177/89cd21c2-9648-11e4-9382-3a963f665843.png)

**Comment by mfrederickson** [comment]
@robp2175 in IE under Tools > Compatibility View Settings, I unchecked the `Display intranet sites in Compatibility View` and then refreshed the page, and it worked just fine.

![image](https://cloud.githubusercontent.com/assets/473165/5650377/52e23ba0-964a-11e4-880e-21bba1816c83.png)

![image](https://cloud.githubusercontent.com/assets/473165/5650393/7aeb2792-964a-11e4-87c4-f63b74915256.png)

**Comment by robp2175** [comment]
I am not using IE, I primarily use Firefox or Chrome. Using Chrome debugger I found this.
![screen shot 01-07-15 at 03 12 pm](https://cloud.githubusercontent.com/assets/8832179/5652516/5d0a306c-967f-11e4-813b-50550202e5ff.PNG)

**Comment by robp2175** [comment]
Here is the result for tail -f /usr/share/concerto/log/production.log | grep concerto_content
<code>I, [2015-01-07T15:26:22.941735 #13439]  INFO -- :   Rendered vendor/plugins/concerto_content_scheduling/app/views/concerto_content_scheduling/content/_schedule.html.erb (1.8ms)
I, [2015-01-07T15:26:23.084589 #13439]  INFO -- : Started GET "/stylesheets/concerto_content_scheduling/application.css" for 10.40.3.57 at 2015-01-07 15:26:23 -0500
ActionController::RoutingError (No route matches [GET] "/stylesheets/concerto_content_scheduling/application.css"):
I, [2015-01-07T15:26:23.091241 #13804]  INFO -- : Started GET "/javascripts/concerto_content_scheduling/application.js" for 10.40.3.57 at 2015-01-07 15:26:23 -0500
ActionController::RoutingError (No route matches [GET] "/javascripts/concerto_content_scheduling/application.js"):
I, [2015-01-07T15:26:23.452728 #13804]  INFO -- : Started GET "/javascripts/concerto_content_scheduling/application.js" for 10.40.3.57 at 2015-01-07 15:26:23 -0500
ActionController::RoutingError (No route matches [GET] "/javascripts/concerto_content_scheduling/application.js"):
I, [2015-01-07T15:26:23.458881 #13447]  INFO -- : Started GET "/stylesheets/concerto_content_scheduling/application.css" for 10.40.3.57 at 2015-01-07 15:26:23 -0500
ActionController::RoutingError (No route matches [GET] "/stylesheets/concerto_content_scheduling/application.css"):</code>

**Comment by robp2175** [comment]
I believe this would be the full error from the log
<pre><code>
I, [2015-01-07T15:28:30.523082 #13447]  INFO -- : Started GET "/javascripts/concerto_content_scheduling/application.js" for 10.40.3.57 at 2015-01-07 15:28:30 -0500
F, [2015-01-07T15:28:30.524313 #13447] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/javascripts/concerto_content_scheduling/application.js"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:16:in `_call'
  vendor/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:12:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:514:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:144:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'


I, [2015-01-07T15:28:30.524937 #13447]  INFO -- : Processing by ErrorsController#render_error as */*
I, [2015-01-07T15:28:30.531501 #7764]  INFO -- : Started GET "/stylesheets/concerto_content_scheduling/application.css" for 10.40.3.57 at 2015-01-07 15:28:30 -0500
F, [2015-01-07T15:28:30.537862 #7764] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/stylesheets/concerto_content_scheduling/application.css"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:16:in `_call'
  vendor/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:12:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:514:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:144:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

</code></pre>

**Comment by mfrederickson** [comment]
Maybe you just need to recompile the assets?  Try running this in the concerto directory

`rake assets:precompile:all RAILS_ENV=production`

**Comment by robp2175** [comment]
concerto@concerto:/usr/share/concerto$ sudo rake assets:precompile:all RAILS_ENV=production
[sudo] password for concerto:
rake aborted!
Don't know how to build task 'assets:precompile:all'

(See full trace by running task with --trace)


Could you please tell me how this plugin is supposed to be installed. I keep thinking that maybe I missed something.

**Comment by mfrederickson** [comment]
One way to install the plugin is to go to plugins in the application and add concerto_content_scheduling as a gem.  Save it and then restart your apache.

Maybe try just this:
`rake assets:precompile RAILS_ENV=production`

**Comment by robp2175** [comment]
Bingo! sudo rake assets:precompile RAILS_ENV=production worked. I am now seeing the popup correctly. Thanks Marvin for the time and patience.


BTW, that is the way I installed the plugin.
